project:
  type: website
  output-dir: docs

website:
  title: "Samuel Bharti"
  navbar:
    left:
      - href: index.qmd
        text: Home
  site-url: "https://samuelbharti.quarto.pub"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
